### ISSUE TITLE
Frontend Checklist

### ISSUE THREAD

**Issue by patrickuhlmann** [CeviBuroAarau/cevi-buchs-rohr-aarau-website#99]
- [ ] Noopener: In case you are using external links with target="_blank", your link should have a rel="noopener" attribute to prevent tab nabbing. If you need to support older versions of Firefox, use rel="noopener noreferrer"
- [ ] Link checker: There are no broken links in my page, verify that you don't have any 404 error.
- [ ] HTML Lint: I use tools to help me analyze any issues I could have on my HTML code.
- [ ] Stylelint: All CSS or SCSS files are without any errors.
- [ ]  CSS Validator: The CSS was tested and pertinent errors were corrected.
- [ ] Lazy loading: Images are lazyloaded (A noscript fallback is always provided).
- [ ] Color contrast: Color contrast should at least pass WCAG AA (AAA for mobile).
- [ ] Accessibility standards testing: Use the WAVE tool to test if your page respects the accessibility standards.
- [ ] Screen reader: All pages were tested in two or more screen readers (such as JAWS, VoiceOver, and NVDA).
- [ ] Google PageSpeed: All your pages were tested (not only the homepage) and have a score of at least 90/100.
- [ ] sitemap.xml: A sitemap.xml exists and was submitted to Google Search Console.
- [ ] robots.txt: The robots.txt is not blocking webpages.

Referenz:
https://frontendchecklist.io/

**Comment by patrickuhlmann** [comment]
Kein Bedarf
